### ISSUE TITLE
readme and documentation

### ISSUE THREAD

**Issue by wrikebotwallah** [croox/generator-wp-dev-env#1]
* edit/update README.md
* needs some documentation and tutorials. Could use either:
  * public github wiki
  * private confluence

**Comment by kuttnerd** [comment]
das würde ich ins öffentliche readme packen, oder?

**Comment by jhotadhari** [comment]
mmm is ja schon älter die issue.

die idee mit github wiki ist lange verworfen.

in der README.md steht ja mittlerweile schon mal das nötigste.
und der rest docs gibts als docset. erzeugt aus dem sourcecode.
und die kickstarter anweisungen gibts in unserem [wiki](https://wiki.croox.com/s/bn0r471g1p5aj8uhe9pg/development/d/bn55tn1g1p5aj8uhefmg/unsere-wordpress-entwicklung?currentPageId=bn61h7hg1p5aj8uhejjg).

sollten wir mal überarbeiten bei zeiten.
ich tu mich immer schwer mit docs schreiben. jetzt wo vllt hoffentlich mehr leute das ding benutzen, können wir die docs auch verbessern.

**Comment by kuttnerd** [comment]
jep, das issue können wir mE closen. ich bastel gern an der "for dummies" version des readmes mit ;-)
hab auch schon ein paar anregungen, ergänze das noch wenn alles soweit mal steht

**Comment by kuttnerd** [comment]
also machs ruhig zu wenns für dich passt ...
