### ISSUE TITLE
dist task does not compress

### ISSUE THREAD

**Issue by jhotadhari** [croox/generator-wp-dev-env#14]

**Comment by jhotadhari** [comment]
https://github.com/croox/wp-dev-env-grunt/commit/866b25c715ded1f59b449fe6c51e3ba995abff26
This will compress js/css on dist task.
But actually the issue is, that config of hooked build tasks is not updated properly.

We'll have to throw away grunt anyway soon. And next solution will do it better.
done

**Comment by kuttnerd** [comment]
gulp, node, webpack or what will it be?
