### ISSUE TITLE
add subgenerator for fonts

### ISSUE THREAD

**Issue by kuttnerd** [croox/generator-wp-dev-env#5]
the goal is local storage of the used fonts to gain pagespeed and be GDPR compliant

**Comment by jhotadhari** [comment]
ist das noch wichtig, oder ab in den done?

denke ein subgenerator wäre nicht der richtige weg, da alle möglichen fonts in den generator integrieren müssten.

vllt besser ein tutorial schreiben, wie man fonts gdpr compliant zufügen kann. entweder in die docset docs oder in das croox wiki

**Comment by kuttnerd** [comment]
jop das ist vernünftiger > ich nehms mal mit in das wiki issue mit auf und hake das hier ab
